### ISSUE TITLE
"Restore default" button hides the HTMLComposition

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/CompositionEditor#25]
### Steps to reproduce

1. Build and run [HelloWorld](https://github.com/starcounterapps/helloworld)
2. Run CompositionEditor and CompositionProvider
3. Open CompositionEditor
4. Edit the composition
5. Click save
6. Click restore default

### Expected result

The default HTMLComposition should be back in the editing field

### Actual result

The editing field is empty

##### Starcounter version 

Starcounter 2.3.1.6633

##### Involved apps' version

HelloWorld @https://github.com/StarcounterApps/HelloWorld/commit/b0d289b37c541fe623d37193dc4473c5e64b0de7
CompositionEditor@https://github.com/Starcounter/CompositionEditor/commit/c9165f427ea34232af8b027f55be66e0cd2ed619
CompositionProvider@https://github.com/Starcounter/CompositionProvider/commit/0433a57917ec373b4410ced3fa745e20a6defcec
 
### Screenshot

![brokenrestoredefault](https://user-images.githubusercontent.com/19392292/27423566-68beed64-5732-11e7-9647-7f07144da236.gif)

CC @tomalec

**Comment by PatrykSzwer** [comment]
I can't reproduce this anymore with BlendingEditor. @Mackiovello could You please check this issue with newest SC and Blending app, and if It's not reproducible close it here since We're moving all issues from CompositionEditor to Blending repository?

**Comment by Mackiovello** [comment]
Tried again with 2.4 and the whole blending suite - I can't reproduce it
