### ISSUE TITLE
Add button to close the editor

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/CompositionEditor#3]
Basically, all programs and pop-ups have a way to close the window by clicking on a close button in the top right or top left corner. It would thus be intuitive to add a simple button that does this to the editor.

**Comment by mmnosek** [comment]
+1 for that topic, I was also looking for some close button :)

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/18
