### ISSUE TITLE
Display the key for the composition in the database

### ISSUE THREAD

**Issue by warpech** [Starcounter/CompositionEditor#31]
When editing the composition, I would like to know the [key](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.Extensions/HTMLComposition.cs#L8) by which it will be saved in the database. 

This way it becomes easier to make notes for exporting/importing of the saved compositions.

Right now the way to do it is to use Chrome Dev Tools Network tab to check the REST API request.

![artboard](https://user-images.githubusercontent.com/566463/28121580-dc624fe2-671b-11e7-91d5-0ad89ada74bc.png)

**Comment by PatrykSzwer** [comment]
Moved to https://github.com/Starcounter/Blending/issues/24
