### ISSUE TITLE
CompositionEditor doesn't seems to work at Starcounter 2.4.0.4138

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/CompositionEditor#48]
On Starcounter 2.4.0.4138, when You run CompositionEditor and click Ctrl+E Shortcut at any app page, compositionEditor tool doesn't show up. I think It's related with https://github.com/Starcounter/Home/issues/338.

cc: @Starcounter/webplatformteam

**Comment by PatrykSzwer** [comment]
I though so. I'll close this issue after Starcounter/Home#338 is done. I just created it in a first place as an information for other users.

**Comment by PatrykSzwer** [comment]
Starcounter/Home#338 is done. Closing.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/CompositionEditor/releases/tag/2.3.0
- published in the App Warehouse
