### ISSUE TITLE
Change default size of the editor icon

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/CompositionEditor#5]
By default, we usually run Composition Editor together with Launcher and SignIn and default composition shows Composition Editor icon just before the current user avatar. Currently, the icon size is different than user avatar (22px) - IMO sizes should be exactly the same in default composition. Let's change it to 24 px, it's default size of Polymer iron icon. From iron-icon documentation: "The iron-icon element displays an icon. By default an icon renders as a 24px square."

The screenshot that illustrates this problem:
![7ed1da80-dcdf-11e6-8502-71661d2d5ee2](https://cloud.githubusercontent.com/assets/4943949/22059908/0f02da8e-dd6f-11e6-8c90-c4a8d5f61590.png)

**Comment by warpech** [comment]
Fix in PR #4
