### ISSUE TITLE
Remove the hacky way to add the editor in HTML root

### ISSUE THREAD

**Issue by warpech** [Starcounter/CompositionEditor#8]
Remove the hacky way to add the editor in HTML root:

https://github.com/Starcounter/CompositionEditor/blob/e2aaa488539f289caac12e2dc4d5ee8ce130d87f/src/CompositionEditor/Program.cs#L24-L32

The hacky way should be replaced with `Blender.MapUrl` to the "root" partial.

**Comment by warpech** [comment]
Requires: https://github.com/Starcounter/Starcounter/issues/4017

**Comment by warpech** [comment]
https://github.com/Starcounter/level1/issues/4017 is now done, it is time to work on this issue now.

**Comment by PatrykSzwer** [comment]
Moved to: https://github.com/Starcounter/Blending/issues/23

**Comment by PatrykSzwer** [comment]
@warpech could you clarify what did you mean by:
`The hacky way should be replaced with Blender.MapUrl to the "root" partial.`
How exactly this Blender.MapUri (right now actually entry in blend.json) should look like/work?
